In [30]:
# 서울시 cctv 설치 현황을 파일에서 가져와서 cctv_seoul 데이터프레임 생성
# 2번째 줄의 내용을 컬럼으로
import pandas as pd

file_path = './dataset/서울시CCTV설치운영현황(자치구)_년도별_211231기준.csv'
cctv_seoul = pd.read_csv(file_path , encoding = 'cp949' , skiprows = 1)

# 구분을 구명, 구분이 '계'인 자료는 삭제
cctv_seoul.rename(columns = {'구분':'구이름'}, inplace = True)
cctv_seoul.set_index('구이름', inplace = True)
cctv_seoul.drop('계',axis = 0 , inplace = True)
cctv_seoul

,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
구이름,,,,,,,,,,,,
종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
중 구,"2,447",16,114,87,77,236,240,372,386,155,361,403
용산구,"2,611",34,71,234,125,221,298,351,125,307,617,228
성동구,"3,829",163,144,208,107,325,255,967,415,490,472,283
광진구,"3,211",35,57,100,187,98,52,675,465,712,175,655
동대문구,"2,628",4,0,14,16,115,804,814,201,218,223,219
중랑구,"3,737",346,21,253,72,132,155,153,174,1049,934,448
성북구,"4,602",81,78,170,229,322,594,890,867,714,253,404
강북구,"3,090",8,0,22,61,124,251,29,391,1078,656,470
도봉구,"1,930",128,22,2,145,172,123,129,222,210,184,593
노원구,"2,492",0,87,164,77,514,331,175,216,320,387,221
은평구,"4,131",14,3,44,332,329,555,403,635,1057,288,471
서대문구,"3,055",730,253,155,108,137,223,356,237,343,397,116
마포구,"2,496",23,19,40,112,185,478,365,373,494,299,108
양천구,"3,650",71,174,158,134,246,424,577,837,312,346,371
강서구,"2,744",54,122,104,202,199,168,506,259,457,356,317
구로구,"4,608",852,216,349,187,268,326,540,488,434,415,533
금천구,"2,411",0,0,174,80,361,133,196,539,367,513,48
영등포구,"4,056",572,136,238,123,209,248,311,658,65,1213,283
동작구,"2,306",41,24,25,503,128,253,271,300,322,419,20
관악구,"5,149",440,84,431,439,609,622,688,674,595,331,236
서초구,"4,082",8,73,79,70,562,504,1041,417,339,433,556
강남구,"6,871",69,67,66,580,830,1293,988,745,791,926,516
송파구,"2,897",40,59,90,85,214,176,241,541,1073,235,143
강동구,"2,809",268,27,227,49,154,202,273,377,356,614,262

In [33]:
# cctv 데이터를 파일로 저장
cctv_seoul.to_csv('./dataset/cctv.csv' , encoding = 'utf-8-sig' , index = None)

In [35]:
df = pd.read_csv('./dataset/cctv.csv')
df

,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
1,"2,447",16,114.0,87.0,77,236,240,372,386,155,361,403
2,"2,611",34,71.0,234.0,125,221,298,351,125,307,617,228
3,"3,829",163,144.0,208.0,107,325,255,967,415,490,472,283
4,"3,211",35,57.0,100.0,187,98,52,675,465,712,175,655
5,"2,628",4,0.0,14.0,16,115,804,814,201,218,223,219
6,"3,737",346,21.0,253.0,72,132,155,153,174,1049,934,448
7,"4,602",81,78.0,170.0,229,322,594,890,867,714,253,404
8,"3,090",8,0.0,22.0,61,124,251,29,391,1078,656,470
9,"1,930",128,22.0,2.0,145,172,123,129,222,210,184,593
10,"2,492",0,87.0,164.0,77,514,331,175,216,320,387,221
11,"4,131",14,3.0,44.0,332,329,555,403,635,1057,288,471
12,"3,055",730,253.0,155.0,108,137,223,356,237,343,397,116
13,"2,496",23,19.0,40.0,112,185,478,365,373,494,299,108
14,"3,650",71,174.0,158.0,134,246,424,577,837,312,346,371
15,"2,744",54,122.0,104.0,202,199,168,506,259,457,356,317
16,"4,608",852,216.0,349.0,187,268,326,540,488,434,415,533
17,"2,411",0,0.0,174.0,80,361,133,196,539,367,513,48
18,"4,056",572,136.0,238.0,123,209,248,311,658,65,1213,283
19,"2,306",41,24.0,25.0,503,128,253,271,300,322,419,20
20,"5,149",440,84.0,431.0,439,609,622,688,674,595,331,236
21,"4,082",8,73.0,79.0,70,562,504,1041,417,339,433,556
22,"6,871",69,67.0,66.0,580,830,1293,988,745,791,926,516
23,"2,897",40,59.0,90.0,85,214,176,241,541,1073,235,143
24,"2,809",268,27.0,227.0,49,154,202,273,377,356,614,262

In [54]:
for col in df.columns :
    df[col].fillna(0, inplace = True)

In [55]:
df

,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,"1,715",815,0.0,0.0,195,150,0,261,85,9,200,0
1,"2,447",16,114.0,87.0,77,236,240,372,386,155,361,403
2,"2,611",34,71.0,234.0,125,221,298,351,125,307,617,228
3,"3,829",163,144.0,208.0,107,325,255,967,415,490,472,283
4,"3,211",35,57.0,100.0,187,98,52,675,465,712,175,655
5,"2,628",4,0.0,14.0,16,115,804,814,201,218,223,219
6,"3,737",346,21.0,253.0,72,132,155,153,174,1049,934,448
7,"4,602",81,78.0,170.0,229,322,594,890,867,714,253,404
8,"3,090",8,0.0,22.0,61,124,251,29,391,1078,656,470
9,"1,930",128,22.0,2.0,145,172,123,129,222,210,184,593
10,"2,492",0,87.0,164.0,77,514,331,175,216,320,387,221
11,"4,131",14,3.0,44.0,332,329,555,403,635,1057,288,471
12,"3,055",730,253.0,155.0,108,137,223,356,237,343,397,116
13,"2,496",23,19.0,40.0,112,185,478,365,373,494,299,108
14,"3,650",71,174.0,158.0,134,246,424,577,837,312,346,371
15,"2,744",54,122.0,104.0,202,199,168,506,259,457,356,317
16,"4,608",852,216.0,349.0,187,268,326,540,488,434,415,533
17,"2,411",0,0.0,174.0,80,361,133,196,539,367,513,48
18,"4,056",572,136.0,238.0,123,209,248,311,658,65,1213,283
19,"2,306",41,24.0,25.0,503,128,253,271,300,322,419,20
20,"5,149",440,84.0,431.0,439,609,622,688,674,595,331,236
21,"4,082",8,73.0,79.0,70,562,504,1041,417,339,433,556
22,"6,871",69,67.0,66.0,580,830,1293,988,745,791,926,516
23,"2,897",40,59.0,90.0,85,214,176,241,541,1073,235,143
24,"2,809",268,27.0,227.0,49,154,202,273,377,356,614,262